f=open("C:/Users/TEMP.MITS.000/Desktop/python",'+a')
f.write('data science')
f.seek(0)
print(f.read())
f.seek(0)
print(f.read(5))
f.seek(0)
print(f.readline())
f.seek(0)
print(f.readlines())
print(f.tell())
f.close()
